# Generated by Django 5.2 on 2025-04-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=10,
                    ),
                ),
                ("endereco", models.CharField(max_length=300)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tipo_atendimento",
                    models.CharField(
                        choices=[
                            ("emergencia", "Emergência"),
                            ("consulta", "Consulta"),
                            ("internacao", "Internação"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condicao_medica", models.CharField(blank=True, max_length=100)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
    ]
