# Generated by Django 5.2 on 2025-04-24 06:42

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_alter_paciente_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="endereco",
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_bairro",
            field=models.CharField(
                default="Desconhecido", max_length=100, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_cidade",
            field=models.CharField(
                default="Cidade Desconhecida", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_complemento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_estado",
            field=models.CharField(default="SP", max_length=2, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_numero",
            field=models.CharField(blank=True, max_length=10, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_rua",
            field=models.CharField(
                default="Rua Desconhecida", max_length=200, verbose_name="Rua"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(validators=[pacientes.models.validate_idade]),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(
                max_length=15, validators=[pacientes.models.validate_telefone]
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="tipo_atendimento",
            field=models.CharField(
                choices=[
                    ("emergencia", "Emergência"),
                    ("consulta", "Consulta"),
                    ("internacao", "Internação"),
                    ("cirurgia", "Cirurgia"),
                    ("exame", "Exame"),
                    ("vacinacao", "Vacinação"),
                ],
                max_length=50,
            ),
        ),
    ]
